on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: python version.py
        - uses: docker/login-action@master
          with:
              username: chaowenguo
              password: ${{secrets.DOCKER}}
        - uses: docker/setup-buildx-action@master
        - uses: docker/build-push-action@master
          with:
              push: true
              tags: chaowenguo/aiohttp
              build-args: VERSION=${{env.VERSION}}
        - uses: docker/build-push-action@master
          with:
              push: true
              context: chat
              tags: chaowenguo/chat:aiohttp
              build-args: VERSION=${{env.VERSION}}
